# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      #      - id: detect-aws-credentials
      - id: pretty-format-json
      - id: debug-statements
      #      - id: name-tests-test
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  #        language_version: python3.12

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [ '--profile', 'black' ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.12
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [ "--ignore=D100,D104,D107,D213,D203,D407" ]
        files: '^(?!(bot/tests/|bot/migrations/|bot/admin|bot/help|bot/vpn|bot/subscription|bot/users)).*\.py$'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-atomicwrites
          - types-tabulate
          - types-freezegun
          - types-pyyaml
          - pydantic>=2.8
          - pydantic-settings
          - sqlalchemy
          - tokenize-rt
          - types-python-dateutil
          - types-aiofiles
        args: [ --strict,
                --ignore-missing-imports,
                --no-warn-unused-ignores
        ]
        exclude: |
          (?x)^(
            venv/|
            bot/tests/|
            build/|
            dist/|
            \.venv/|
            bot/migrations/|
            bot/admin|
            bot/vpn|
            bot/subscription|
            bot/users
          )
