services:
  vpn_bot:
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: [ "CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/bot/health', timeout=2)" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - shared_net
      - infrastructure_net
  nginx_vpn_bot:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/www/certbot:/var/www/certbot:ro   # Монтируем директорию с хоста
      - /etc/letsencrypt:/etc/letsencrypt:ro # Путь к сертификатам, если используете Certbot
      - /etc/ssl/private/dhparam.pem:/etc/ssl/private/dhparam.pem:ro  # Монтируем файл DH параметров
      - static_files1:/usr/src/app/static # Подключение статических файлов
      - static_files2:/usr/src/app/templates  # Подключение шаблонов Jinja2
    networks:
      - shared_net
      - infrastructure_net
networks:
  shared_net:
    name: shared_net
    external: true
  infrastructure_net:
    name: infrastructure_net
    driver: bridge
    external: true
