services:
  vpn_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn_bot
    restart: always
    environment:
      TZ: Europe/Moscow
    volumes:
      - vpn_bot_logs:/vpn_bot/bot/logs
      - static_files1:/vpn_bot/.venv/lib/python3.12/site-packages/sqladmin
      - static_files2:/vpn_bot/bot/templates
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          memory: 128M

  nginx_vpn_bot:
    image: nginx:latest
    container_name: nginx_vpn_bot
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 128M
volumes:
  vpn_bot_logs:
    name: vpn_bot_logs
  static_files1:
    name: static_files1
  static_files2:
    name: static_files2
