services:
  vpn_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn_bot
    restart: always
    environment:
      TZ: Europe/Moscow
    volumes:
      - vpn_bot_logs:/vpn_bot/bot/logs
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          memory: 128M
    networks:
      - infrastructure_net

  nginx_proxy_test:
    image: nginx:latest
    container_name: nginx_proxy_test
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_test.conf:/etc/nginx/nginx.conf:ro
      - /var/www/certbot:/var/www/certbot:ro   # Монтируем директорию с хоста
      - /etc/letsencrypt:/etc/letsencrypt:ro # Путь к сертификатам, если используете Certbot
      - /etc/ssl/private/dhparam.pem:/etc/ssl/private/dhparam.pem:ro  # Монтируем файл DH параметров
      - static_files1:/usr/src/app/static # Подключение статических файлов
      - static_files2:/usr/src/app/templates  # Подключение шаблонов Jinja2
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 128M
    networks:
      - infrastructure_net
volumes:
  vpn_bot_logs:
    name: vpn_bot_logs
  static_files1:
    name: static_files1
  static_files2:
    name: static_files2

networks:
  infrastructure_net:
    name: infrastructure_net
    driver: bridge
    external: true
